name: quiz
description: Application d'apprentissage gÃ©ographique avec quiz des drapeaux et capitales

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flip_card: ^0.7.0
  confetti: ^0.7.0
  connectivity_plus: ^5.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/icons/